[server]
port = 8501
headless = false

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false

[runner]
magicEnabled = false

[logger]
level = "info"

[theme]
base = "light"
primaryColor = "#4F8BF9"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#31333F"
font = "sans serif"
